# Change these first
owner: Henrik-3 # Your GitHub username
repo: api-status # Your GitHub repository name

# Add your sites here
sites:
  - name: VALORANT Ingame API
    url: http://138.201.180.68/ingame/status
  - name: General API
    url: https://api.henrikdev.xyz/main/status

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.henrikdev.xyz
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: API Status
  introTitle: 
  introMessage: 
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
