# Change these first
owner: Henrik-3 # Your GitHub username
repo: api-status # Your GitHub repository name

# Add your sites here
sites:
  - name: VALORANT Ingame API
    url: http://138.201.180.68/ingame/status
  - name: General API
    url: https://api.henrikdev.xyz/main/status
    
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

status-website:
  theme: dark
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.henrikdev.xyz
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: API Status
  introTitle: 
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: VALORANT API
      href: https://github.com/Henrik-3/unofficial-valorant-api
    - title: Rocket League API
      href: https://github.com/Henrik-3/unofficial-rocket-league-api
    - title: Rainbow Six Siege API
      href: https://github.com/Henrik-3/unofficial-rainbow-six-siege-api

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
